language: julia
os: 
  - linux
julia:
  - 1.6
branch:
  onky:
    - master
notifications:
  email: false
jobs:
  include:
    - stageï¼š "Documentation"
      julia: 1.6
      os: linux
      scipt:
        - julia --project=docs/ -e 'using Pkg; Pkg.instantiate();
                                   Pkg.develop(PackageSpec(path=pwd()))'
        - julia --project=docs/ docs/make.jl
      after_success: skip
